### ISSUE TITLE
[Gridsquare Maps] Add Flag to include eQSL results

### ISSUE THREAD

**Issue by g4klx** [magicbug/Cloudlog#1548] opened 2022-07-27 21:16 UTC
This is using the hosted version of the development version of Cloudlog.

If a QSO has been confirmed via LoTW then it appears to be completely confirmed, in particular the grid square count is updated and the grid square is shown in green.

However if the only QSO for a grid square has only been confirmed via eQSL then the grid square remains unconfirmed despite the arrows for eQSL both being green. The QSO is indeed confirmed with eQSL itself when I log into it.

Is this a bug or a feature?

**Comment by magicbug** [comment] 2022-07-27 21:20
Its by design, I should add a flag but as eqsl isn't accepted for vucc I just ignore it

**Comment by g4klx** [comment] 2022-07-27 21:23
It would be good to add it as a flag as it could/would still mean something to the operator though.

**Comment by AndreasK79** [comment] 2023-06-29 09:41
@g4klx this one is fixed in the dev branch. I rewrote the Gridsquare Map with more filters:
![image](https://github.com/magicbug/Cloudlog/assets/6977712/492ae5c5-6323-4d8e-8b8a-6848e3c746ac)

**Closed by AndreasK79** 2023-06-29 09:41 UTC
Labels: Feature
