### ISSUE TITLE
Feature Request: Public OQRS Service 

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#1700] opened 2022-10-18 20:08 UTC
It would be nice if cloud log would offer a public OQRS service for each station log. 

How could it work? 

There is a page like https://url-to-cloudlog/index.php/oqrs/dl1abc which allows to search for a callsign and QSO-date. Then there appear different buttons (can be configured) to request QSL via Bureau, Direct, etc... 

The requested QSOs will be marked as requested in the database.

**Comment by magicbug** [comment] 2022-10-18 21:09
Its a great idea and something I want to add as it would be handy for special events I'm part of

**Comment by AndreasK79** [comment] 2022-10-24 17:38
A VERY early teaser:
![image](https://user-images.githubusercontent.com/6977712/197590375-00eebcf5-cc87-4207-be04-ff904f94ff1a.png)

**Comment by magicbug** [comment] 2022-10-26 12:41
Liking this very much, I'm wondering if this should be part of public or if a general /oqrs section might be the most suitable with option of doing /oqrs/callsign

Liking it so far!

**Comment by AndreasK79** [comment] 2022-10-26 12:52
Another teaser:
![image](https://user-images.githubusercontent.com/6977712/198030658-0964c36d-3a23-43de-bb2c-b0c2aa5d0a5b.png)

**Comment by AndreasK79** [comment] 2022-10-26 12:54
Only front-end has been worked on so far. Nothing is saved in the database yet.

**Comment by AndreasK79** [comment] 2022-10-26 13:10
I need to create a migration script and code for activating oqrs on station location. When that is done, I can make a draft PR so that others can test it out, and make suggestions.

**Comment by magicbug** [comment] 2022-10-26 20:33
Sounds good, think this will be a very popular feature

**Comment by AndreasK79** [comment] 2022-10-27 09:32
#1724 has been added as a draft. Feedback welcome.

**Comment by AndreasK79** [comment] 2022-10-29 11:01
As I am not a QSL manager, and I don't deal with OQRS, I'm not sure how the user interface should be, but in my mind, I'm thinking something like this:
![image](https://user-images.githubusercontent.com/6977712/198827633-7b6c65b7-9a06-48b2-9d47-1f170628c901.png)
Split on station_id. Then split on request callsign.

I would like to have some logic that tries to find a matching qso.
This is far from done, but I'm connection bits and pieces.

Any thoughts anyone?

**Comment by dg9vh** [comment] 2022-10-29 11:42
Be some kind of tolerant at the time value. Plus/minus 5 to 10 Minutes would be ok

**Comment by AndreasK79** [comment] 2022-10-29 12:29
Yes. Was thinking +- 15 minutes. Also button to search for call. I was also thinking about viewing log for all calls worked within that timeframe to look for busted calls and not in log requests.

**Comment by myzinsky** [comment] 2022-10-29 13:26
@AndreasK79 Do I get this screenshot right? This would be the internal view?

So the user will see a list of accepted QSOs and the user has to acknowledge each QSO again manually, i.e. set it to "Requested" manually? 

I'm not sure if this would be feasible for big event stations, for example. So the more automatically the better I think?

Maybe we should check the commercial OQRS systems how they work under the hood... anybody experience?

**Comment by AndreasK79** [comment] 2022-10-29 14:01
@myzinsky yes, internal view.

I guess this could be the view that contains not in log requests and those where the date/time does not match. Those who match, could be automatically flagged as requested. But how would you know who requested bureau, and who requested direct? I'm not aware of any flag for that...

**Comment by AndreasK79** [comment] 2022-11-05 13:10
#1724 is at a state where it can be tested now. Feedback is very much appreciated.

1. OQRS is enabled in station location.
2. Email alert is enabled in station location. Email settings need to be set in global options.
3. QSL information is set in station location.
4. If a match for a QSO is found, it is marked as requested in the database.
5. You can see a list of the open requests in admin and oqrs requests.
6. The ones that are matched, are found in print requested qsls.
7. OQRS can be set as done or deleted.
8. I've added buttons to check for all QSOs with the call.
9. You can also see all QSOs within 30 minutes of the time submitted.

**Comment by phl0** [comment] 2022-11-05 17:55
I tested the current state and found a bug I believe:

![Screenshot 2022-11-05 185238](https://user-images.githubusercontent.com/7112907/200134258-261f8944-6f64-46f4-a951-e7c42eee3b7c.jpg)

I wanted to request OQRS for a single QSO where multiple were found. Imho it should ignore the QSOs where I didn't enter date and time. But form what I see it tries to also update them and rans into a database error because date and time for those are empty.

**Comment by AndreasK79** [comment] 2022-11-05 19:10
@phl0 I agree. Those with no date/time should not be saved. My setup just saved them here with no error, so I didn't think too much about it.

I can think of 3 issues right now:
1. No checking is done for request. Should check that at least 1 QSO is filled, and email is filled.
2. Do not try to save request where date/time is not filled when multiple QSOs are found.
3. Currently there are no place to view the message for a request where the QSO was found. Since these are marked as done, and QSO is set to requested, they will not show up in the list. I don't know how this should be handled. Suggestions?

**Comment by AndreasK79** [comment] 2022-11-05 20:50
1 and 2 are fixed now.

**Comment by AndreasK79** [comment] 2022-11-06 18:18
3 is also fixed. Added so that OQRS info can be viewed from QSL Print.

**Comment by phl0** [comment] 2022-11-07 10:11
Can report that the issue with selecting only one QSO of many works now. Requests are created and emails send. Only the Page listing OQRS requests stays empty ...

![Screenshot from 2022-11-07 11-11-48](https://user-images.githubusercontent.com/7112907/200284442-567cac2f-8034-4adf-8ae6-fed93d581f26.png)

**Comment by phl0** [comment] 2022-11-07 10:12
> Added so that OQRS info can be viewed from QSL Print.

What do you think about adding a link to OQRS on the visitors site (See https://github.com/AndreasK79/Cloudlog/pull/14)?

**Comment by AndreasK79** [comment] 2022-11-07 10:19
> Can report that the issue with selecting only one QSO of many works now. Requests are created and emails send. Only the Page listing OQRS requests stays empty ...

Yes, that is by design. Completed OQRS are now shown here. They are marked as done, and marked for QSLprint.

**Comment by AndreasK79** [comment] 2022-11-07 10:24
> > Added so that OQRS info can be viewed from QSL Print.
> 
> What do you think about adding a link to OQRS on the visitors site (See [AndreasK79#14](https://github.com/AndreasK79/Cloudlog/pull/14))?

Thanks for testing and feedback.

I like the idea. However, a check for active OQRS needs to be added, and only print if active.

**Comment by phl0** [comment] 2022-11-07 10:27
> I like the idea. However, a check for active OQRS needs to be added, and only show if active.

Roger makes sense. Will add that.

**Comment by phl0** [comment] 2022-11-07 11:57
Added with https://github.com/AndreasK79/Cloudlog/pull/14/commits/92b1c844d61feeb43af7e7d9803a6146dd7c1fc3. Please test.

**Comment by AndreasK79** [comment] 2022-11-07 15:48
It's working, but what if the public page (and logbook) you are visiting, does not have OQRS enabled? You will then show an OQRS-link, but you will not find the call in the dropdown on the OQRS page.

**Comment by magicbug** [comment] 2022-12-26 21:22
Being as this features now active closing this issue.

**Closed by magicbug** 2022-12-26 21:22 UTC
Labels: Feature, Help Wanted
