### ISSUE TITLE
"Check QSOs missing DXCC data" checks all QSOs

### ISSUE THREAD

**Issue by dk2ro** [magicbug/Cloudlog#1934] opened 2023-01-16 19:24 UTC
**Describe the bug**
Hitting the "Check QSOs missing DXCC data" button should check all QSOs where no DXCC information is available. But instead it will check every single QSO in the log. Depending on log size, this operation is going to take some time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Admin -> Update Country Files
2. Click on 'Check QSOs missing DXCC data'

**Expected behaviour**
Only QSOs with no DXCC information should be checked.

**Additional context**
I think the problem could arise from the default value set here:
https://github.com/magicbug/Cloudlog/blob/394597a11d9135df46d92020cb355c2e9036b226/application/controllers/Update.php#L235
In conjunction with the isset statement here:
https://github.com/magicbug/Cloudlog/blob/394597a11d9135df46d92020cb355c2e9036b226/application/models/Logbook_model.php#L2960

**Comment by AndreasK79** [comment] 2023-01-23 08:22
Yeah, that doesn't work as intended.

Removing isset in logbook_model seems to be the way to go:
`if (!$all){`

**Comment by AndreasK79** [comment] 2023-01-23 09:30
Pushed fix to dev.

**Closed** 2023-01-24 07:52 UTC
