### ISSUE TITLE
new update killed public access

### ISSUE THREAD

**Issue by kd4six** [magicbug/Cloudlog#1668] opened 2022-10-14 13:50 UTC
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
going to the page now loads a log-in screen, instead of the public access version of the log

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to my logbook: https://kd4six.cloudlog.co.uk

**Expected behaviour**
load the publicly accessible log / search page, without having to log in.

**Comment by magicbug** [comment] 2022-10-14 13:55
Not a bug, correct behaviour.

- Create a Station Logbook
- Assign it a public slug 
- on the main station list you'll then see a globe that is now your public URL for the logbook
- 
![chrome_4EndhiN4Kb](https://user-images.githubusercontent.com/84308/195864215-9cb975d8-66d8-413a-8971-58ed779dddad.png)

**Closed by magicbug** 2022-10-14 13:55 UTC

**Comment by kd4six** [comment] 2022-10-14 14:16
OK, I just did this, and it does show a publicly accessible page, but no search feature on that page? I'm doing something wrong, I'm sure :(
