### ISSUE TITLE
Live Contest Logging: New QSOs do not appear in QSO list after saving

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#2139] opened 2023-05-14 12:09 UTC
If you are in the Live Contest Logging view and you enter a new QSO I would expect the QSO to appear below in the "Contest Logbook" list after saving.

However the list is not updated.

It is only updated after I leave the Live QSO logging view and reenter it.

Same is true for the "Post Contest Logging" view.

**Comment by AndreasK79** [comment] 2023-05-14 13:24
I can't reproduce this problem here. It will filter on current callsign when entering a call, but once that is logged, all QSOs will show in the table.

Do you get any error messages in devtools (F12) ?

**Comment by phl0** [comment] 2023-05-14 14:16
Cannot reproduce here either ... Keen to see what your dev tools reveal.

**Comment by phl0** [comment] 2023-05-14 14:21
This is how it looks here:

https://www.youtube.com/watch?v=IJxMAdVLX8s

(I did log two test QSOs in that contest before starting the recording).

**Comment by m0urs** [comment] 2023-05-14 17:47
I guess I know what is happening. As long as you do not leave the Contest Log view, everything is ok. Just leave the view and then return to that view later and start to enter new QSOs.

Now the QSOs are displayed successfully but ... they are added to the END of the view:

![image](https://github.com/magicbug/Cloudlog/assets/2588362/46d1c49d-fffd-48bd-b634-cbbacba69685)

I did not look at the end but only at the beginning of the view and therefore though they are not displayed at all.

So my expectation would be that new QSOs are always displayed at the top of the QSO list even after you left the view between two sessions.

**Comment by AndreasK79** [comment] 2023-05-23 10:13
@m0urs #2161 should fix this. At least it did in my tests. Could you give it a go?

**Comment by m0urs** [comment] 2023-05-23 15:45
> @m0urs #2161 should fix this. At least it did in my tests. Could you give it a go?

Seems to work for me now correctly. Thanks.

However: I do no longer get a "duplicate" warning!? I switched back to the current "dev" branch and I would say, in this branch there is the same issue. So it seems that it is not you last change which broke it but something before?

**Comment by m0urs** [comment] 2023-05-23 15:50
Steps to reproduce th eissue:

- Add 2 Contest QSOs (the duplicate warning appears correctly)
- Switch to the normal live QSO view and add a normal (non-contest) QSO
- Switch to the Live Contest QSO view
- Add a duplicate callsign (worked before in the contest): The duplicate warning does not appear.

**Comment by AndreasK79** [comment] 2023-05-23 18:27
I've merged the table fix.

I can't duplicate the worked before problem. I tried doing exactly what you described, and I get worked before. Not sure what is going on here. Did you reset the contest session?

**Comment by m0urs** [comment] 2023-05-23 20:28
You are right, I cannot reproduce it now either with the most current Dev branch. No idea what I did wrong before. I tried it with a private browser session also so it should not have been a cache issue. 

Thanks for fixing the sorting issue.

**Comment by petrkr** [comment] 2023-08-28 12:57
I have same issue in latest dev (in time of writting commit from 27th Aug). If I add log, nothing appear in table at bottom, but all QSO I can find at Dashboard then.

**Comment by petrkr** [comment] 2023-08-28 13:13
Well here are errors:

Both are related to datetime object which is returns bool, from documentation it return false on failure, so it probably does not parsed datetime well..

```
<p>Type: Error</p>
<p>Message: Call to a member function format() on bool</p>
<p>Filename: /var/www/devcloudlog/application/models/Contesting_model.php</p>
<p>Line Number: 16</p>
```

but why date variable is bool I do not know


```
<p>Type: Error</p>
<p>Message: Call to a member function format() on bool</p>
<p>Filename: /var/www/devcloudlog/application/models/Contesting_model.php</p>
<p>Line Number: 221</p>
```

**Comment by magicbug** [comment] 2023-08-28 13:26
I've removed seconds in the PR at https://github.com/magicbug/Cloudlog/pull/2447 if someones able to confirm this resolves it

**Comment by petrkr** [comment] 2023-10-04 15:03
I checked latest dev branch and it still occurs... 

As I found, problem is only if you press "Start new contest" too early in Live (seconds are not present yet by timer) or if you start new contest in Post Contest, where seconds are not pre-filled.

Possible solutions are: 
 - during javascript send add missing seconds
 - prefill seconds to those forms on load

better will be add missing seconds, because especially at Post one users will NOT fill seconds at all by hand.

**Comment by iu2frl** [comment] 2023-11-26 18:26
I just tested in 2.5.2 as well as dev and both in "live contest" and "post contesting" if i click "save qso" the content of the page is refreshed but nothing happens, qso is not logged either in my logbook or in the contest logbook down below

**Comment by magicbug** [comment] 2024-01-14 18:05
Believe i found the issue, fresh new contest when adding QSO table stayed blank but now shows QSOs

**Closed by magicbug** 2024-01-14 18:05 UTC
