### ISSUE TITLE
PHP error when trying to update missing grid

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#2741] opened 2023-11-28 22:43 UTC
**Describe the bug**
When trying to update QSOs that are missing the gridsquare, I'm getting a PHP error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to /update/check_missing_grid
2. A PHP error results for each QSO missing a grid

**Error Message**

A PHP Error was encountered

Severity: Warning

Message: Undefined array key "gridsquare"

Filename: models/Logbook_model.php

Line Number: 4061

**Server info**

    Cloudlog dev branch
    Ubuntu: 22.04.3
    PHP: 8.3
    Apache: 2.4.54
    MySQL: 8.0.35-0ubuntu0.22.04.1

**Comment by phl0** [comment] 2023-11-29 14:16
Fixed with https://github.com/magicbug/Cloudlog/pull/2745.

**Comment by HB9HIL** [comment] 2023-11-29 15:04
@ofadam 

Please check and close if the issue is gone. Fix is in 'dev' branch 😁

**Comment by ofadam** [comment] 2023-11-29 16:14
Hmm.. I'm now getting a long list of "Error: Callsign not found" errors when trying to update grids.

**Comment by phl0** [comment] 2023-11-29 16:27
> Hmm.. I'm now getting a long list of "Error: Callsign not found" errors when trying to update grids.

Yepp. Thats the case where the callsign does not have an entry in the callbook you are querying (qrz or hamqth).

**Comment by ofadam** [comment] 2023-11-29 16:29
Was that failing silently before recently? I don't remember seeing that error before. No biggie if just a visual change.

**Comment by phl0** [comment] 2023-11-29 16:35
The error has not been handled before. The code assumed that the answer always contained a grid which obviously is not the case. Now we are passing the error from the upstream callbook (e.g. qrz) to the user.

**Comment by phl0** [comment] 2023-11-30 11:33
@ofadam Can you confirm it is fixed? If so please close the issue. Tnx =)

**Closed** 2023-12-07 19:00 UTC
