### ISSUE TITLE
On editing QSO it's not possible to add WWFF data

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#1686] opened 2022-10-15 13:46 UTC
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
On editing QSO it's not possible to add WWFF data

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a QSO
2. Click on Edit QSO
3. Click on Awards
4. Paste GFF-0107 in the WWFF textbox
5. Click Save
6. Nothing happens

**Expected behaviour**
I expect it to save the WWFF reference in the WWFF field. Or perhaps I'm mistaking about the use of the WWFF field. Because in other cases I can see the SIG and SIG info field being used.
When using QSO > Post QSO the field populates accordingly expectations

**Screenshots**
<img width="546" alt="Schermafbeelding 2022-10-15 om 10 44 04" src="https://user-images.githubusercontent.com/60810525/195989679-e630e46d-a5c1-4e27-b318-e6d78bc6cc5b.png">

<img width="334" alt="Schermafbeelding 2022-10-15 om 15 38 26" src="https://user-images.githubusercontent.com/60810525/195989684-53767bf1-a3a9-4a46-9f35-199d0adc6b31.png">

**Desktop (please complete the following information):**
 - MAC OS Monterey
 - Safari
 - 16

**Comment by magicbug** [comment] 2022-10-15 13:51
Yep can confirm this is a bug you cant change the WWFF field when editing.

.. waves at @phl0

**Comment by phl0** [comment] 2022-10-15 14:57
Roger. Please assign to me (cannot do that myself). Will have a look. Tnx for reporting this.

**Comment by phl0** [comment] 2022-10-15 16:16
Tnx @AndreasK79. Seems this is not a bug but the operator missed to install the necessary WWFF data as per update function. See: https://github.com/magicbug/Cloudlog/wiki/Recommended-Cron-Jobs. 

I can reproduce the issue on my end if the WWFF data has not been loaded. But as soon as the data is loaded I can edit the QSO as requested:

![Screenshot from 2022-10-15 18-14-28](https://user-images.githubusercontent.com/7112907/195996878-e64f0715-2965-4617-9a6e-d847c07d2ba5.png)

Please update WWFF data and try again. If solved please close here. Thank you.

**Comment by magicbug** [comment] 2022-10-15 16:51
Confirmed this resolves it

Run the background task which is `/index.php/update/update_wwff` and it resolves it.

**Closed** 2022-10-15 20:50 UTC
